### ISSUE TITLE
.NET CORE 6 Problem

### ISSUE THREAD

**Issue by danielhojnacki25** [Chronostasys/ServerSideCropperExample#1]
Hi! I am using net core v.6 on my Blazor Server Side project. 
Crooper not working on this version. Why?
![Capture](https://user-images.githubusercontent.com/63186076/158695547-01b4e346-d194-46b1-9204-1810462a8346.PNG)

**Comment by Chronostasys** [comment]
Hi @danielhojnacki25 , thanks you for reporting this issue. I tested it on my pc and seems like it's [a bug  of Asp.Net Core 6](https://github.com/dotnet/aspnetcore/issues/38842). So before blazor team officially fixing this issue, I would recommend you to use client side version or turn back to dotnet 5.

**Comment by Chronostasys** [comment]
Added a [walkaround](https://github.com/Chronostasys/Blazor.Cropper/issues/43#issuecomment-1155504333) in v1.2.6.
